import { SocialMention, SourceFetchResult } from '@/types/social-listening';

const MOCK_TWEETS: SocialMention[] = [
  {
    id: 'tw-001',
    platform: 'twitter',
    author: '@tecnoargentina',
    authorFollowers: 45200,
    content: 'Increíble la nueva promo de Frávega en Smart TVs 📺 Compramos un Samsung 55" a mitad de precio. El envío llegó en 24hs. #Frávega #Ofertas',
    url: 'https://x.com/tecnoargentina/status/001',
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    engagement: { likes: 342, shares: 89, comments: 45, views: 12400 },
    sentiment: 'muy_positivo',
    topics: ['promociones', 'smart-tv', 'envío-rápido'],
    reach: 45200,
  },
  {
    id: 'tw-002',
    platform: 'twitter',
    author: '@consumidor_ar',
    authorFollowers: 12800,
    content: 'Llevo 3 días esperando respuesta del servicio técnico de @Fravega por una heladera que vino fallada. Pésima atención post-venta. #Reclamo',
    url: 'https://x.com/consumidor_ar/status/002',
    timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    engagement: { likes: 567, shares: 234, comments: 189, views: 34500 },
    sentiment: 'muy_negativo',
    topics: ['servicio-técnico', 'post-venta', 'reclamo', 'heladera'],
    reach: 12800,
  },
  {
    id: 'tw-003',
    platform: 'twitter',
    author: '@marialopez_ba',
    authorFollowers: 890,
    content: 'Fui a Frávega del shopping y me atendieron muy bien. El vendedor sabía todo sobre los lavarropas. Recomiendo 👍',
    url: 'https://x.com/marialopez_ba/status/003',
    timestamp: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    engagement: { likes: 23, shares: 5, comments: 8 },
    sentiment: 'positivo',
    topics: ['atención-presencial', 'lavarropas', 'recomendación'],
    reach: 890,
  },
  {
    id: 'tw-004',
    platform: 'twitter',
    author: '@ofertas_ya',
    authorFollowers: 98000,
    content: '🔥 HOT SALE en Frávega: hasta 40% en notebooks y tablets. Mejores precios que Garbarino y Musimundo. Link en bio #HotSale2026',
    url: 'https://x.com/ofertas_ya/status/004',
    timestamp: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    engagement: { likes: 1200, shares: 567, comments: 234, views: 89000 },
    sentiment: 'positivo',
    topics: ['hot-sale', 'notebooks', 'tablets', 'comparativa-precios'],
    reach: 98000,
  },
  {
    id: 'tw-005',
    platform: 'twitter',
    author: '@juanperez_tech',
    authorFollowers: 5400,
    content: 'La app de Frávega anda cada vez peor. Se cuelga cuando querés pagar, perdés el carrito. Arreglen eso @Fravega',
    url: 'https://x.com/juanperez_tech/status/005',
    timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    engagement: { likes: 189, shares: 78, comments: 92, views: 15600 },
    sentiment: 'negativo',
    topics: ['app-móvil', 'bugs', 'experiencia-compra'],
    reach: 5400,
  },
  {
    id: 'tw-006',
    platform: 'twitter',
    author: '@electrohogar_ar',
    authorFollowers: 23400,
    content: 'Frávega lanzó su nueva línea de electrodomésticos sustentables. Clase A en eficiencia energética. Buena movida 🌱 #Sustentabilidad',
    url: 'https://x.com/electrohogar_ar/status/006',
    timestamp: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    engagement: { likes: 456, shares: 123, comments: 67, views: 28000 },
    sentiment: 'positivo',
    topics: ['sustentabilidad', 'eficiencia-energética', 'electrodomésticos'],
    reach: 23400,
  },
  {
    id: 'tw-007',
    platform: 'twitter',
    author: '@defensa_consumidor_ya',
    authorFollowers: 67000,
    content: 'Nuevo reclamo colectivo contra Frávega por demoras en entregas del CyberMonday. Ya son más de 200 casos reportados. #DerechoDelConsumidor',
    url: 'https://x.com/defensa_consumidor_ya/status/007',
    timestamp: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    engagement: { likes: 2300, shares: 1200, comments: 567, views: 145000 },
    sentiment: 'muy_negativo',
    topics: ['reclamo-colectivo', 'entregas', 'cybermonday', 'defensa-consumidor'],
    reach: 67000,
  },
];

export async function fetchTwitterMentions(keywords: string[]): Promise<SourceFetchResult> {
  // Simulate API latency
  await new Promise(resolve => setTimeout(resolve, 300));

  return {
    platform: 'twitter',
    mentions: MOCK_TWEETS,
    fetchedAt: new Date().toISOString(),
    success: true,
  };
}
